# Generated by Django 3.0.2 on 2020-03-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='say_hi',
            field=models.BooleanField(default=False),
        ),
    ]
