# Generated by Django 3.0.2 on 2020-03-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_say_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expire_pass',
            field=models.BooleanField(default=True),
        ),
    ]
