# Generated by Django 2.2 on 2020-05-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200430_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visit',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
