# Generated by Django 2.2 on 2020-04-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0010_auto_20200426_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='text',
        ),
    ]
