# Generated by Django 2.2 on 2020-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0013_workingarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingarea',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
