# Generated by Django 2.2 on 2020-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0014_workingarea_sort'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='visit',
            new_name='sort',
        ),
        migrations.RemoveField(
            model_name='company',
            name='working_area',
        ),
        migrations.AddField(
            model_name='company',
            name='working_area',
            field=models.ManyToManyField(blank=True, null=True, to='prerequisites.WorkingArea'),
        ),
    ]
