# Generated by Django 2.2 on 2020-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='title',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
