# Generated by Django 2.2 on 2020-05-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertises', '0002_advertise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='en_title',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
